// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFr-G2ugcSjRihOK3ewLeCTFQDIClWUuU',
    appId: '1:234634132223:web:f41fdbb85aacbf7aef6aca',
    messagingSenderId: '234634132223',
    projectId: 'flutter-firebase-auth-8ec4a',
    authDomain: 'flutter-firebase-auth-8ec4a.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-8ec4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeaS3yzZeytOolL9WTOqZllJ0tqgqQvLM',
    appId: '1:234634132223:android:4c8f6640fe7b9936ef6aca',
    messagingSenderId: '234634132223',
    projectId: 'flutter-firebase-auth-8ec4a',
    storageBucket: 'flutter-firebase-auth-8ec4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuSiOspPn-Qxwr5nUBV8A-xl3l95c-cAY',
    appId: '1:234634132223:ios:52a6668332a7a9f8ef6aca',
    messagingSenderId: '234634132223',
    projectId: 'flutter-firebase-auth-8ec4a',
    storageBucket: 'flutter-firebase-auth-8ec4a.firebasestorage.app',
    androidClientId: '234634132223-gs5v5q4s8evj9gep9ufbrr11sqt1a3fl.apps.googleusercontent.com',
    iosClientId: '234634132223-587pljlt0d8mhc55b7oeod7a93557eei.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuSiOspPn-Qxwr5nUBV8A-xl3l95c-cAY',
    appId: '1:234634132223:ios:52a6668332a7a9f8ef6aca',
    messagingSenderId: '234634132223',
    projectId: 'flutter-firebase-auth-8ec4a',
    storageBucket: 'flutter-firebase-auth-8ec4a.firebasestorage.app',
    androidClientId: '234634132223-gs5v5q4s8evj9gep9ufbrr11sqt1a3fl.apps.googleusercontent.com',
    iosClientId: '234634132223-587pljlt0d8mhc55b7oeod7a93557eei.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFr-G2ugcSjRihOK3ewLeCTFQDIClWUuU',
    appId: '1:234634132223:web:3180c0e89f4d61b4ef6aca',
    messagingSenderId: '234634132223',
    projectId: 'flutter-firebase-auth-8ec4a',
    authDomain: 'flutter-firebase-auth-8ec4a.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-8ec4a.firebasestorage.app',
  );
}
